### ISSUE TITLE
Add an option to reset the music

### ISSUE THREAD

**Issue by bgiesing** [corbindavenport/wii-shop-extension#10]
Personally I don't like that the music keeps playing from where you left off, it would be nice to have an option to restart the music every time you switch to a shopping site (perhaps also with an option to also set a time limit so it only resets after X minutes)

**Comment by TheTechRobo** [comment]
Or a manual reset, like #8

**Comment by corbindavenport** [comment]
Yeah, the default behavior should probably be to reset the music when leaving the shopping tab.

**Comment by livejamie** [comment]
It would be nice for an option to only have it play once, lol.

**Comment by TheTechRobo** [comment]
@livejamie then what's the point of having the extension?

**Comment by livejamie** [comment]
> @livejamie then what's the point of having the extension?

It's still fun to have it play once when I open Amazon/eBay, etc.

**Comment by corbindavenport** [comment]
The new 2.0 update restarts music playback after switching between tabs, which fixes the original issue here. I've also made a separate issue (#21) for the no-looping suggestion, so this can be closed now.
