### ISSUE TITLE
Exclude current site doesn't work

### ISSUE THREAD

**Issue by Lebon14** [corbindavenport/wii-shop-extension#120]
Hi.

I go a lot on Discogs and I don't necessarily shop there so I put the website on the exclusion list.
Still, the extension still plays the shop music even if it's excluded. To stop it, I have to drag the volume to 0.

Using latest public release of firefox (102.0.1)

Cheers.

**Comment by rarDevelopment** [comment]
Could you include a screenshot of the excluded sites list?

**Comment by Lebon14** [comment]
Hi. Sorry for the delay.
I did better. I just did a video detailing my current issues with the extension:
https://youtu.be/Yu4a5_pyQxk

Hope that helps.

**Comment by rarDevelopment** [comment]
I just tried in Firefox, it's working as expected for me. In your video, I notice that your button always said "Turn background music on" which suggests that it was set to off. Not sure what that means, but I'd check on if it still looks that way.

**Comment by Lebon14** [comment]
> I just tried in Firefox, it's working as expected for me. In your video, I notice that your button always said "Turn background music on" which suggests that it was set to off. Not sure what that means, but I'd check on if it still looks that way.

Well, I want the music to play but not on Discogs...

**Comment by corbindavenport** [comment]
I can't duplicate on the testing version in the `dev` branch that will roll out soon. I'll close this for now, feel free to comment or re-open if you still notice it.
