### ISSUE TITLE
Add popular greek tech store websites

### ISSUE THREAD

**Issue by GIKAS123** [corbindavenport/wii-shop-extension#133]
Some of the most popular ones are:
plaisio.gr
kotsovolos.gr
public.gr
consoleclub.gr
gameexplorers.gr

Many thanks in advance!

**Comment by corbindavenport** [comment]
Thanks, this has been added to the list repo: https://github.com/corbindavenport/shop-list/commit/96145564258c246fa6a3007b77e9242d0976068d
