### ISSUE TITLE
Add option to disable and enable extension

### ISSUE THREAD

**Issue by EdTheNerd** [corbindavenport/wii-shop-extension#17]
It would be nice to have an option to toggle the extension on the right of the address bar like other plugins.

I love having it play but if I'm trying to listen to something else I have to keep going into chromes settings and disabling the plugin entirely, then turning it back on later.

**Comment by corbindavenport** [comment]
I have this working in the `master` branch, it will be in the next release.

![image](https://user-images.githubusercontent.com/3879063/150668921-5df503be-cb0f-49f4-b24b-ec0de74b276a.png)

**Comment by corbindavenport** [comment]
This is now rolled out as part of v2.0, closing.
