### ISSUE TITLE
Experimenting with auto-detection of shopping websites

### ISSUE THREAD

**Issue by DylanGTech** [corbindavenport/wii-shop-extension#19]
I noticed that the list of websites that trigger the music are, despite being very commonly-used shopping hubs, limited if you prefer shopping from smaller distributors or directly from manufacturers rather than huge shopping hubs like Amazon or Ebay. This made me consider the concept of having the software auto-detect when someone is either in the process of completing a purchase, browsing a website (or portion of a website), and play it then.

Here is a theoretical way of implementing it:

The following checks are performed asynchronously when going to a new page
- The URL contains one or more keywords that are practically exclusive to shopping websites, such as "shop", "purchase", "buy", etc.
- A form is detected on the webpage with similar sets of keywords, or with inputs that are practically exclusive to shopping websites
- Check for currency within the page. For example, dollar amounts and optional strikethroughs/percentages off to signify a "deal"
For each unique instance of this (repeats would ideally be filtered out), a certain number of points are awarded. After which, if the sum exceeds a certain threshold, the webpage is deemed to be a "shopping website", or that you are otherwise purchasing something with that page. If the music isn't already playing, it fades in, and when you leave, and this process comes up negative, it fades out.

Would be a fun thing to try in my opinion.

To state for the record, I have not used this extension myself yet. Have only browsed the code after noticing a pal of mine starred it. It's the little things that make an open-source project good, you know?

**Comment by corbindavenport** [comment]
Auto-detection is a cool idea, but it's over-engineering that would be more prone to causing intended results (like you mentioned). I think adding the ability for people to add their own websites (#23) will address this.
