### ISSUE TITLE
Doesn't work with Amazon Smile

### ISSUE THREAD

**Issue by JosephTico** [corbindavenport/wii-shop-extension#3]
Domain: `smile.amazon.com`

Similar domains exists for UK: `smile.amazon.co.uk`.

**Comment by corbindavenport** [comment]
Someone just submitted a PR that fixes this: https://github.com/corbindavenport/wii-shop-extension/pull/4

I'll merge it once I get some free time.

**Comment by corbindavenport** [comment]
This should now be fixed, as of the v1.1 update.
