### ISSUE TITLE
Play wii sounds when click on links and validate payment

### ISSUE THREAD

**Issue by elpaulo** [corbindavenport/wii-shop-extension#30]
Would be cool to add some sounds when you navigate on the site.

https://www.youtube.com/watch?v=rMDW4jYuYAU

At 0:53 : When you finalize your order
At 0:56 : Flip page
At 1:15 : Back to front page

etc etc...

As i write this, i realize it can be nearly impossible to do because every site is different. Maybe implement this in the most famous ones like amazon ?

**Comment by TheTechRobo** [comment]
It might be plausible to use common classnames/ids used for checkout, buy, frontpage,... buttons.  Especially in common engines like squarespace wix shopify et al

**Comment by corbindavenport** [comment]
This is a fun idea, but I'm trying not to make the codebase too complex. This behavior would also have to be programmed for each site, and would break whenever the sites change their URLs.
