### ISSUE TITLE
Add videogame stores

### ISSUE THREAD

**Issue by Obspogon** [corbindavenport/wii-shop-extension#34]
Obvious idea. Examples:

- Steam, GOG, Epic Store
- Console stores: Nintendo, Playstation, Xbox
- Third-party: Humble Bundle, GreenManGaming

I was going to suggest Bandcamp, but actually, that's a bad idea

**Comment by corbindavenport** [comment]
Yeah this is a good idea, as long as the entire domain is for a store (e.g. the Nintendo eShop is still on Nintendo.com, so that wouldn't work).

**Comment by Omiod** [comment]
You could check the path too, so that it matches with https://www.nintendo.com/games/buy-digital/

**Comment by Adamillo** [comment]
Why would it not work if the site was Nintendo.com?

**Comment by corbindavenport** [comment]
I just merged a few pull requests that included game sites, I think all the big ones are in there now. If someone notices one is missing, please make a new issue or pull request :)
