### ISSUE TITLE
Add Japanese stores and proxies

### ISSUE THREAD

**Issue by Fuffley** [corbindavenport/wii-shop-extension#35]
Because Nintendo is based in Japan, It only makes sense for second hand Japanese sites like Yahoku, Mercari, Rakuten, Yahoo Shopping, etc. and proxies to use them outside of Japan like ZenMarket, Buyee, FromJapan, etc.

**Comment by Fuffley** [comment]
To have this shopping theme. (Idk why I cut it like that)

**Comment by EmqsaGit** [comment]
i think you should link some stores then?

**Comment by TheTechRobo** [comment]
You could also add the sites manually to the site list in the js folder, and make a pull request if you want

**Comment by Fuffley** [comment]
https://auctions.yahoo.co.jp/
https://jp.mercari.com/
https://zenmarket.jp/
https://buyee.jp/
https://suruga-ya.jp
https://suruga-ya.com

**Comment by corbindavenport** [comment]
Done, these sites will be included in the next update.
