### ISSUE TITLE
Canadian websites

### ISSUE THREAD

**Issue by AtillatheBun** [corbindavenport/wii-shop-extension#43]
examples being that bestbuy.com works but bestbuy.ca doesn't. It works on Amazon but some others do not work.

**Comment by Lebon14** [comment]
I think an easier way to do this would just be for us to have an easy way to add websites to a list.

**Comment by corbindavenport** [comment]
@Lebon14 Yeah, I'm planning to implement that in #23.

**Comment by corbindavenport** [comment]
After merging a bunch of pull requests, there are now some Canadian websites included. If anyone knows sites that aren't included, let me know or make a new PR :)
