### ISSUE TITLE
Have music resume where it left off when switching back to shopping tab

### ISSUE THREAD

**Issue by Majestano** [corbindavenport/wii-shop-extension#45]
This seems a bit at odds with https://github.com/corbindavenport/wii-shop-extension/issues/10 but goes along with https://github.com/corbindavenport/wii-shop-extension/pull/4 in that I'd prefer the music to resume where it left off when you switch back to your shopping tab after clicking another tab instead of restarting each time. An option to choose between restart or resume on tab focus could be a good compromise.

**Comment by Majestano** [comment]
Stealing off of SAUZ#9999 on the discord, could also have it still play silently in the background when on another tab if that's possible

**Comment by alkaris2** [comment]
A suggestion to add to this, if it's to be made to resume playing instead of restarting, you could have it fade-in and fade-out when switching between tabs.

**Comment by corbindavenport** [comment]
Discussed this on Discord, but resuming on tab switch was the original behavior in v1.0 (and 1.1 maybe?). This was changed to the current behavior for two reasons:

1. There were a few requests for the current behavior, and it makes more sense IMO. If you go a while between shopping and the music picks back up where it left off hours (or days) later, it can be more jarring.
2. The current version doesn't just stop the music when you switch tabs, it also deletes the `source` element from the background audio player, which releases your browser's (and keyboard's) media controls from the Wii Shop music, so controlling playback on YouTube or other open sites works again.

There are ways to engineer around both of those issues, but I don't want to over-complicate the code, so I'm keeping this as-is for now. The Manifest V3 rewrite (#7) might also make resuming playback the easier option, so this might change down the road.

**Comment by agoode** [comment]
Another option could be to resume unless a period of time (30 seconds?) has elapsed, otherwise start over.
