### ISSUE TITLE
Add volume slider to settings

### ISSUE THREAD

**Issue by Pandawan** [corbindavenport/wii-shop-extension#5]
I don't know how feasible this is, but it'd be nice to have some kind of volume slider/option

**Comment by corbindavenport** [comment]
There's already a PR that adds a popup menu interface: https://github.com/corbindavenport/wii-shop-extension/pull/2

It wouldn't be much additional work to implement a volume slider.

**Comment by corbindavenport** [comment]
Merging this issue into #8.

**Comment by bleck9999** [comment]
#8 is now closed with no mention of changing music volume, is this still planned?

**Comment by corbindavenport** [comment]
Oops, I missed that. I'll re-open this issue, it's still something that should be easy to do.

**Comment by ProstoSanja** [comment]
created a minimal solution in #51 a week ago, @corbindavenport

**Comment by corbindavenport** [comment]
This was fixed in the v2.1 release, forgot to close this issue.
