### ISSUE TITLE
Brazilian stores

### ISSUE THREAD

**Issue by EmqsaGit** [corbindavenport/wii-shop-extension#54]
Idunno how i should write this down since there's no template, but, basically, i tested the extension on brazilian store websites, and none of them seemed to work, so i'll send *here* a list of stores that i think should be added... And, if possible, it would be nice to have a text box to add your own websites on the extension/addon menu... Anyways, the list:

https://www.mercadolivre.com.br/
https://shopee.com.br/ (not sure if shopee is brazilian, but it sure has a .com.br soooo)
https://pt.aliexpress.com/ (not brazilian but missing)
https://www.kabum.com.br/
https://www.pichau.com.br/
https://www.chipart.com.br/
https://www.cea.com.br/
https://www.avon.com.br/
https://www.lojasrenner.com.br/
https://www.marisa.com.br/
https://www.kalunga.com.br/
https://www.nintendo.com/games/ (not brazilian, but SOMEHOW missing, how the main inspiration is missing? lol)
https://www.apple.com/br/ (not _just_ brazilian, but missing, not sure if it applies. Worth noting: Apple has MANY domains)
https://www.iplace.com.br/
https://www.webstore.com.br/ (not a webstore, but if it provides sub-domains, i _guess_ it should be added just to be safe, since it allows you to _make_ webstores)
https://www.americanas.com.br/
https://www.pontofrio.com.br/
https://www.casasbahia.com.br/
https://www.magazineluiza.com.br/ (i _think_ that's also a store in other countries, but, .com.br)
https://www.netshoes.com.br/
https://www.zattini.com.br/
https://www.dafiti.com.br/roupas/
https://www.carrefour.com.br/ (multi-national but .com.br domain)

I think tha's it for now... these are the most used ones, i think

**Comment by TheTechRobo** [comment]
Some of these can't be added. Paths (e.g. nintendo.com/games) can't be added currently; we'd have to add nintendo.com completely and that won't do. ~~I also didn't add webstore.com.br since I'm not sure if this extension does subdomains (although i'm 99% sure).~~ Added.

**Comment by EmqsaGit** [comment]
yay thanks

**Comment by EmqsaGit** [comment]
dunno why was it closed, guess i misclicked
