### ISSUE TITLE
Replace the old DSi theme with a newer one

### ISSUE THREAD

**Issue by Adamillo** [corbindavenport/wii-shop-extension#61]
This audio from this video is outdated: https://www.youtube.com/watch?v=krISRDj6_2w
There's a better version of this music by Toru The Red Fox which used a hacked DSi hardware for the most accurate audio. It gets rid of the loading sound from the beginning. It's also extended so it loops properly too but the file size would be a tiny bit larger. Here's the video: https://www.youtube.com/watch?v=lttQ47yZ-5A&t=207s

**Comment by qfoxb** [comment]
Addressed by #58
