### ISSUE TITLE
Include mercadolibre to shopping websites

### ISSUE THREAD

**Issue by frixed** [corbindavenport/wii-shop-extension#63]
Please include mercadolibre to shopping websites

**Comment by EmqsaGit** [comment]
i guess my list of Brazilian webstores already includes mercadolivre.com.br, and... it's "mercadolibre"

**Comment by frixed** [comment]
> 

Yeah but the brazilian version is "mercadolivre" millwile the argentinian and other countries version is "mercadolibre"

**Comment by EmqsaGit** [comment]
oh

Em qui, 3 de fev de 2022 12:26 PM, frixed ***@***.***>
escreveu:

**Comment by corbindavenport** [comment]
I just merged some pull requests that added a bunch of mercadolibre domains, I think this is fixed now. The sites should be detected in the next update.
