### ISSUE TITLE
Add the ability to start the song off with the initial beat, then loop afterwards

### ISSUE THREAD

**Issue by Collserra** [corbindavenport/wii-shop-extension#72]
Not sure how easy/feasible this is, but in the source material for the original Wii eShop, it starts off with that 5-beat track ,then kicks into the loop we're all familiar with. Is this possible to re-create?

Link to a clip with the start in it:
https://youtu.be/yyjUmv1gJEg

**Comment by TheTechRobo** [comment]
We could have two segments per file: an "intro" OGG, and a "loop" one

**Comment by corbindavenport** [comment]
This would be possible to recreate, but yeah it would make playback a fair bit more complicated. We would need two audio file for each song with this functionality, as @TheTechRobo mentioned, and the source attribute on the media playback element would have to be swapped during playback. It would be a fun effect, but not something I want to implement right now.
