### ISSUE TITLE
It's a damned crime

### ISSUE THREAD

**Issue by MochaChocha667** [corbindavenport/wii-shop-extension#74]
to not have https://www.nintendo.com/games/buy-digital/ as a compatible website.

**Comment by TheTechRobo** [comment]
This has been mentioned in mutliple issues. **Partial paths cannot be detected.** Nintendo would have to have a subdomain like store.nintendo.com, otherwise the entire nintendo.com will have the music

**Comment by corbindavenport** [comment]
Closing as duplicate for #13

**Comment by rinsuki** [comment]
JP Store is hosted in subdomain! https://store-jp.nintendo.com
