### ISSUE TITLE
Chrome doesn't view the audio from the tab 

### ISSUE THREAD

**Issue by Alispezzate** [corbindavenport/wii-shop-extension#75]
Chrome doesn't view the audio from the tab so I cannot mute it quickly, for example when I use youtube:
![image](https://user-images.githubusercontent.com/38697944/153229149-49ec1f26-6f31-4bc9-8b06-ac690b841368.png)
a quick toggle pops up to mute the audio but when I open amazon there's none:
![image](https://user-images.githubusercontent.com/38697944/153229278-bc2adf47-01be-4aef-9bbf-102b0da41a94.png)

I know this will probably take too much work but I just wanted to point it out just in case

**Comment by TheTechRobo** [comment]
That's because the extension doesn'T add audio to the tab

It adds audio to its own background window that the extension includes

May be fixed by #7

**Comment by corbindavenport** [comment]
Correct, the music isn't coming from the tab itself, it's coming from a background page. Moving the music to the tab itself would cause it to stop between loading pages, and it would require the extension to need permission to modify all webpages.

The latest update added a button to temporarily mute playback, so if you have the Wii Shop extension toolbar button pinned to your toolbar, that's only two clicks.
