### ISSUE TITLE
Add popup UI and settings page

### ISSUE THREAD

**Issue by corbindavenport** [corbindavenport/wii-shop-extension#8]
The extension should have some basic settings available through the toolbar popup, like a mute button and volume slider. Ideally, Chrome's own media controls should be hidden once this is implemented, which might require switching to the [Web Audio API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Using_Web_Audio_API).

The settings page should have the following options, synchronized with the `chrome.storage.sync` API:

- [x] Track selector with more options
- [ ] Option to import a custom audio file (maybe)
- [ ] Text box for adding websites manually, a comma-separated list might be best

**Comment by danbopes** [comment]
👍 I would like the ability to add my own sites (Like slickdeals.net). A UI would be nice.

**Comment by corbindavenport** [comment]
Track selector is now rolled out as part of the v2.0 update.

**Comment by corbindavenport** [comment]
For easier planning, I'm breaking out the remaining items here into #22 and #23.
