### ISSUE TITLE
New websides

### ISSUE THREAD

**Issue by Makloficz** [corbindavenport/wii-shop-extension#83]
Hello can these websides added? 

https://allegro.pl/
https://botland.com.pl/
https://www.x-kom.pl/
https://www.ceneo.pl/
https://www.mediaexpert.pl/
https://mediamarkt.pl/
https://www.olx.pl/
https://www.morele.net/
https://www.komputronik.pl/

**Comment by corbindavenport** [comment]
Done, these will be included in the next update.
