### ISSUE TITLE
Mercado Libre Issue/bug

### ISSUE THREAD

**Issue by BeyBladey** [corbindavenport/wii-shop-extension#90]
Mercado Libre Issue (.ar)
Mercado Libre seems to change url according to _what you are doing on the website._ (Brain cells dying trying to write)
Seems like there are these prefix (prefix.mercadolibre.com) :
* home.
* producto.
* articulo.
* myaccount.
* listado.

**Comment by TheTechRobo** [comment]
I thought that this extension looked for subdomains too?

**Comment by corbindavenport** [comment]
@TheTechRobo No, subdomains have to be specifically mentioned, which is intended behavior (a lot of shopping sites are on a subdomain only).

**Comment by TheSh466Y** [comment]
This issue happens to with falabella.com and mercadolibre.cl and its prefixes

In the case of falabella.com the prefixes are:

tienda
sodimac
tottus
linio

**Comment by qfoxb** [comment]
i've just gone and added the subdomains to all mercado libre domains in the sitelist in my pull request #97 
Also, did the same with falabella.

**Comment by BeyBladey** [comment]
Opera GX reports this:
"Error handling response: TypeError: Failed to construct 'URL': Invalid URL
Contexto
_generated_background_page.html
Seguimiento de la pila
js/background.js:75 (checkMusic)
js/background.js:100 (función anónima)"
Pretty much any post will throw this error, this one shown with this [url](https://articulo.mercadolibre.com.ar/MLA-729795257-rele-relay-bobina-220v-alterna-30a-normal-abierto-4-pines-_JM#reco_item_pos=2&reco_backend=machinalis-homes-pdp-boos&reco_backend_type=function&reco_client=home_navigation-recommendations&reco_id=1c2d0cb8-e8a8-4723-8d0d-b07fdedefc74&c_id=/home/navigation-recommendations/element&c_element_order=3&c_uid=38e96079-dab4-4edd-9b9e-d204e4e2ea46)

**Comment by qfoxb** [comment]
I'm getting this too now, there must be an invalid URL somewhere in the list
