### ISSUE TITLE
Add some music

### ISSUE THREAD

**Issue by olivertzeng** [corbindavenport/wii-shop-extension#92]
https://www.youtube.com/watch?v=3Tf2hgrnw2M
https://www.youtube.com/watch?v=IfFDotW-jnw

**Comment by TheTechRobo** [comment]
https://github.com/corbindavenport/wii-shop-extension/blob/master/CONTRIBUTING.md

No new music. The extension already has 10 tracks included, and that will probably be it. The ability to import custom music may be implemented in the future.

**Comment by corbindavenport** [comment]
Closing as duplicate of #23
