### ISSUE TITLE
Add the ability to mute other tabs that are playing audio and then unmute them once you switch off the shop tab.

### ISSUE THREAD

**Issue by ShatteredEdgeith** [corbindavenport/wii-shop-extension#94]
I often have music playing in another tab and would like for that tab to be muted and just listen to the nice Wii Shop music.

**Comment by corbindavenport** [comment]
I'll check the extension APIs again to make sure, but I'm fairly sure this isn't possible without having access to the contents of every page in every tab, which would require more invasive permissions.

**Comment by ShatteredEdgeith** [comment]
Damn, oh well. Was worth an ask.
