### ISSUE TITLE
Add marketplace.secondlife.com

### ISSUE THREAD

**Issue by corbindavenport** [corbindavenport/wii-shop-extension#95]
https://marketplace.secondlife.com/

Suggested on Discord.

**Comment by qfoxb** [comment]
I thought the extension didn't work for subdomains, wouldn't the whole second life website have to be added?

**Comment by corbindavenport** [comment]
The extension supports subdomains, they just have to be explicitly stated. For example, `store.elementary.io` is in the list, which only matches that subdomain and not the whole `elementary.io` site.
